export type NameModeType =
    'new_lua_class'
    | 'new_lua_table'
    | 'new_field'
    | 'new_value'
    | 'new_function'
    | 'new_method'
    | 'new_parameter'
    | 'edit_class'
    | 'edit_field'
    | 'edit_value'
    | 'edit_function'
    | 'edit_method'
    | 'edit_parameter'
    | null;
